include:
  - project: 'makeorg/infrastructure/pipeline/templates'
    file: 'pipelines/monorepo.yml'

# Variable
variables:
  APP_NAME: assembly-ui
  APP_WORKSPACE: '@make.org/assembly-ui'
  IMAGE_NAME: $NEXUS_URL/assembly-ui-beta
  IMAGE_APP_TARGET: app-production
  IMAGE_APP_PATH: apps/assembly-ui/Dockerfile
  RUNDECK_JOB_ID: $RUNDECK_ASSEMBLY_UI_BETA_JOB_ID

# Stage
stages:
  - deploy

# Workflow
workflow:
  rules:
    - !reference [.rules, on-merge-request]
    - !reference [.rules, on-protected-branch]

# Rule
.rules-env:
  on-assembly-ui-beta-preproduction:
    if: $CI_COMMIT_BRANCH == "assembly-ui-beta-preproduction"
  on-assembly-ui-beta-production:
    if: $CI_COMMIT_BRANCH == "assembly-ui-beta-production"

# Template
.on-assembly-ui-beta-preproduction:
  rules:
    - !reference [.rules-env, on-assembly-ui-beta-preproduction]
.on-assembly-ui-beta-production:
  rules:
    - !reference [.rules-env, on-assembly-ui-beta-production]

# Environment
.preprod:
  extends: .on-assembly-ui-beta-preproduction
  environment: preproduction

.prod:
  extends: .on-assembly-ui-beta-production
  environment: production
  when: manual

# Deploy
deploy-assembly-ui-beta-preproduction:
  extends:
    - .deploy
    - .preprod
  script:
    - echo $RUNDECK_JOB_ID

deploy-assembly-ui-beta-production:
  extends:
    - .deploy
    - .prod
