version: "3.9"

services:
    app_make_dev:
      image: appmakedev
      build:
        context: .
        dockerfile: apps/front/Dockerfile
        target: dev
      ports:
        - 3000:3000
        - 8888:8888
      volumes:
        &default_volumes
        - .:/home/app
        - /home/app/node_modules
        - /home/app/apps/front/node_modules
        - /home/app/apps/widget/node_modules
        - /home/app/api/node_modules
        - /home/app/components/node_modules
        - /home/app/types/node_modules
        - /home/app/assets/node_modules
        - /home/app/utils/node_modules
        - /home/app/ui/node_modules
        - /home/app/store/node_modules
        - /home/app/apimock/node_modules
        - /home/app/apps/front/dist
      profiles: 
        - dev
  
    app_api_mock:
      image: appapimock
      build:
        context: .
        dockerfile: apps/front/Dockerfile
        target: apimock
      ports:
        - 9000:9000
      volumes: *default_volumes
      profiles: 
        - test
    
    app_make_test:
      image: appmaketest
      build:
        context: .
        dockerfile: apps/front/Dockerfile
        target: test
      ports:
        - 9009:9009
      volumes: *default_volumes
      profiles: 
        - test
