export enum CARD {
  CARD_TYPE_PROPOSAL = 'PROPOSAL_CARD',
  CARD_TYPE_EXTRASLIDE_INTRO = 'EXTRASLIDE_INTRO_CARD',
  CARD_TYPE_EXTRASLIDE_PUSH_PROPOSAL = 'EXTRASLIDE_PUSH_PROPOSAL_CARD',
  CARD_TYPE_EXTRASLIDE_FINAL_CARD = 'EXTRASLIDE_FINAL_CARD',
  CARD_TYPE_EXTRASLIDE_SPECIAL_FINAL_CARD = 'EXTRASLIDE_SPECIAL_FINAL_CARD',
  CARD_TYPE_EXTRASLIDE_DEMOGRAPHICS_CARD = 'EXTRASLIDE_DEMOGRAPHICS_CARD',
  CARD_TYPE_NO_PROPOSAL_CARD = 'NO_PROPOSAL_CARD',
  FEED_PROPOSAL = 'FEED_PROPOSAL',
  FEED_TOP_PROPOSALS = 'FEED_TOP_PROPOSALS',
}
