export enum DATE {
  DATE_CAPITALIZE_L_FORMAT = 'L',
  DATE_CAPITALIZE_LL_FORMAT = 'LL',
  DATE_LOWERCASE_LL_FORMAT = 'll',
  DATE_DD_MMMM_FORMAT = 'DD MMMM',
  DATE_DD_MMMM_YYYY_FORMAT = 'DD MMMM YYYY',
  DATE_MMMM_YYYY_FORMAT = 'MMMM YYYY',
}
