export enum FORM {
  LOGIN_FORMNAME = 'login',
  REGISTER_FORMNAME = 'register',
  REGISTER_PANEL_FORMNAME = 'register-panel',
  LEGAL_CONSENT_FORMNAME = 'legal_consent',
  FORGOT_PASSWORD_FORMNAME = 'forgot_password',
  PASSWORD_RECOVERY_FORMNAME = 'password_recovery',
  PASSWORD_UPDATE_FORMNAME = 'password_update',
  PROFILE_UPDATE_FORMNAME = 'profile_update',
  NEWSLETTER_UPDATE_FORMNAME = 'newsletter_update',
  DATA_POLICY_CONSENT = 'data_policy_consent',
  PROFILE_DELETE_ACCOUNT_FORMNAME = 'profile_delete_account',
  PERSONALITY_OPINION_FORMNAME = 'personality_opinion',
  SEARCH_FORMNAME = 'search',
  PROPOSAL_SUBMIT_FORMNAME = 'proposal_submit',
  FILTER_AND_SORT = 'filter_and_sort',
  COUNTRY_LANGUAGE_SWITCH_FORMNAME = 'country_language_switch',
}
