export enum MODAL_TYPES {
  MODAL_LOGIN = 'MODAL_LOGIN',
  MODAL_REGISTER = 'MODAL_REGISTER',
  MODAL_FORGOT_PASSWORD = 'MODAL_FORGOT_PASSWORD',
  MODAL_PROPOSAL_SUCCESS = 'MODAL_PROPOSAL_SUCCESS',
  MODAL_COUNTRIES = 'MODAL_COUNTRIES',
  MODAL_DEPARTMENT = 'MODAL_DEPARTMENT',
}
