export enum NOTIF {
  // Banner
  ACTIVATION_SUCCESS_MESSAGE = 'ACTIVATION_SUCCESS_MESSAGE',
  ACTIVATION_FAILURE_MESSAGE = 'ACTIVATION_FAILURE_MESSAGE',
  ACCOUNT_DELETION_SUCCESS_MESSAGE = 'ACCOUNT_DELETION_SUCCESS_MESSAGE',
  PASSWORD_RECOVERY_FAILURE_MESSAGE = 'PASSWORD_RECOVERY_FAILURE_MESSAGE',
  LOGIN_SUCCESS_MESSAGE = 'LOGIN_SUCCESS_MESSAGE',
  LOGOUT_SUCCESS_MESSAGE = 'LOGOUT_SUCCESS_MESSAGE',
  REGISTER_SUCCESS_MESSAGE = 'REGISTER_SUCCESS_MESSAGE',
  REGISTER_SUCCESS_VALIDATE_MESSAGE = 'REGISTER_SUCCESS_VALIDATE_MESSAGE',
  SECURE_EXPIRED_MESSAGE = 'SECURE_EXPIRED_MESSAGE',
  UNEXPECTED_ERROR_MESSAGE = 'UNEXPECTED_ERROR_MESSAGE',
  NETWORK_ERROR_MESSAGE = 'NETWORK_ERROR_MESSAGE',
  VOTE_ONLY_MESSAGE = 'VOTE_ONLY_MESSAGE',
  SOCIAL_MEDIA_COOKIES_MESSAGE = 'SOCIAL_MEDIA_COOKIES_MESSAGE',
  COOKIES_PREFERENCES_UPDATE_MESSAGE = 'COOKIES_PREFERENCES_UPDATE_MESSAGE',
  LOGIN_SOCIAL_MISSING_EMAIL_DATA = 'LOGIN_SOCIAL_MISSING_EMAIL_DATA',

  // Tip
  FIRST_VOTE_TIP_MESSAGE = 'FIRST_VOTE_TIP_MESSAGE',
  NOTIFICATION_LEVEL_INFORMATION = 'information',
  NOTIFICATION_LEVEL_SUCCESS = 'success',
  NOTIFICATION_LEVEL_ERROR = 'error',
  NOTIFICATION_LEVEL_ALERT = 'alert',
}
