export const ADD_FEED_ITEM = 'ADD_FEED_ITEM';
export const UPDATE_ITEM_CHUNKS = 'UPDATE_ITEM_CHUNKS';
export const UPDATE_ITEM_TEXT = 'UPDATE_ITEM_TEXT';
export const REMOVE_FEED_LAST_ITEM = 'REMOVE_FEED_LAST_ITEM';
export const START_STREAM = 'START_STREAM';
export const STOP_STREAM = 'STOP_STREAM';
