// autogenerated code - DONT'T EDIT THIS FILE
export const summary = {
  criteria: {
    successOk: 54,
    successKo: 18,
    successNa: 34,
    pourcentOk: 75,
    total: 106,
  },
  test: {
    successOk: 115,
    successKo: 23,
    successNa: 119,
    pourcentOk: 83,
    total: 257,
  },
};
