export const CARD_TYPE_PROPOSAL = 'PROPOSAL_CARD';
export const CARD_TYPE_EXTRASLIDE_INTRO = 'EXTRASLIDE_INTRO_CARD';
export const CARD_TYPE_EXTRASLIDE_PUSH_PROPOSAL = 'EXTRASLIDE_PUSH_PROPOSAL_CARD';
export const CARD_TYPE_EXTRASLIDE_FINAL_CARD = 'EXTRASLIDE_FINAL_CARD';
export const CARD_TYPE_EXTRASLIDE_SPECIAL_FINAL_CARD = 'EXTRASLIDE_SPECIAL_FINAL_CARD';
export const CARD_TYPE_EXTRASLIDE_DEMOGRAPHICS_CARD = 'EXTRASLIDE_DEMOGRAPHICS_CARD';
export const CARD_TYPE_NO_PROPOSAL_CARD = 'NO_PROPOSAL_CARD';

export const FEED_PROPOSAL = 'FEED_PROPOSAL';
export const FEED_TOP_PROPOSALS = 'FEED_TOP_PROPOSALS';
