export const MODAL_LOGIN = 'MODAL_LOGIN';
export const MODAL_REGISTER = 'MODAL_REGISTER';
export const MODAL_FORGOT_PASSWORD = 'MODAL_FORGOT_PASSWORD';
export const MODAL_DEPARTMENT = 'MODAL_DEPARTMENT';
export const MODAL_PROPOSAL_SUCCESS = 'MODAL_PROPOSAL_SUCCESS';
export const MODAL_COUNTRIES = 'MODAL_COUNTRIES';
