// Banner
export const ACTIVATION_SUCCESS_MESSAGE = 'ACTIVATION_SUCCESS_MESSAGE';
export const ACTIVATION_FAILURE_MESSAGE = 'ACTIVATION_FAILURE_MESSAGE';
export const ACCOUNT_DELETION_SUCCESS_MESSAGE =
  'ACCOUNT_DELETION_SUCCESS_MESSAGE';
export const PASSWORD_RECOVERY_FAILURE_MESSAGE =
  'PASSWORD_RECOVERY_FAILURE_MESSAGE';
export const LOGIN_SUCCESS_MESSAGE = 'LOGIN_SUCCESS_MESSAGE';
export const LOGOUT_SUCCESS_MESSAGE = 'LOGOUT_SUCCESS_MESSAGE';
export const REGISTER_SUCCESS_MESSAGE = 'REGISTER_SUCCESS_MESSAGE';
export const REGISTER_SUCCESS_VALIDATE_MESSAGE =
  'REGISTER_SUCCESS_VALIDATE_MESSAGE';
export const SECURE_EXPIRED_MESSAGE = 'SECURE_EXPIRED_MESSAGE';
export const UNEXPECTED_ERROR_MESSAGE = 'UNEXPECTED_ERROR_MESSAGE';
export const NETWORK_ERROR_MESSAGE = 'NETWORK_ERROR_MESSAGE';
export const VOTE_ONLY_MESSAGE = 'VOTE_ONLY_MESSAGE';
export const SOCIAL_MEDIA_COOKIES_MESSAGE = 'SOCIAL_MEDIA_COOKIES_MESSAGE';
export const COOKIES_PREFERENCES_UPDATE_MESSAGE =
  'COOKIES_PREFERENCES_UPDATE_MESSAGE';

// Tip
export const FIRST_VOTE_TIP_MESSAGE = 'FIRST_VOTE_TIP_MESSAGE';

export const NOTIFICATION_LEVEL_INFORMATION = 'information';
export const NOTIFICATION_LEVEL_SUCCESS = 'success';
export const NOTIFICATION_LEVEL_ERROR = 'error';
export const NOTIFICATION_LEVEL_ALERT = 'alert';
