export const enum PANEL_CONTENT {
  REGISTER,
  LOGIN,
  PROPOSAL_JOURNEY,
  PROPOSAL_SUCCESS,
  PROPOSAL_SUCCESS_REGISTER,
  PASSWORD_FORGOT,
  PROPOSAL_AUTHENTICATION,
  REGISTER_CONFIRMATION,
  REGISTER_CONFIRMATION_SOCIAL,
  PROPOSAL_SUBMIT,
  REPORT_TRANSLATION_CONFIRMATION,
}
