---
COMMON_PARAMETERS:
  parameters: []

DISPLAY-PAGE:
  key: display-page
  description: Display of a page
      #purpose: Adoption - DAU measurement (daily active users) 
  parameters: 
    - key: event_slug
      description: The event slug
      purpose: Subject segmentation - improving service
      example: convention-fin-de-vie
      recipients: ['product']
    - key: page
      description: Page name
      example: event-page
      purpose: Measuring the number of visitors to a page
      recipients: ['product']
    - key: language
      description: Interface language
      purpose: Language segmentation - improving service
      recipients: ['product']
        # purpose: Engagement mesurement (by visitors, session)
    - key: assembly_event_id
      description: The event identifier
      purpose: Engagement by event
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['business']
    - key: visitor_id
      description: Unique visitor identifier
      purpose: Segmentation by unique visitor
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['business']
    - key: session_id
      description: Session identifier
      purpose: Segmentation by session
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['business']
      # purpose: Visitors, visits by utms
    - key: assembly_event_id
      description: The event identifier
      purpose: Data for control purpose
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['acquisition']
    - key: visitor_id
      description: Unique visitor identifier
      purpose: Segmentation by unique visitor
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['acquisition']
    - key: session_id
      description: Session identifier
      purpose: Segmentation by session
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['acquisition']
    - key: utm_campaign
      description: Identifies a specific product promotion or strategic campaign
      purpose: Acquisition campaign follow-up
      example: convention_france
      optional: true
      recipients: ['acquisition']
    - key: utm_source
      description: Identifies which site sent the traffic, and is a required parameter.
      purpose: Acquisition campaign follow-up
      example: google
      optional: true
      recipients: ['acquisition']
    - key: utm_term
      description: Identifies search terms
      purpose: Acquisition campaign follow-up
      example: running+shoes
      optional: true
      recipients: ['acquisition']
    - key: utm_content
      description: Identifies what specifically was clicked to bring the user to the site, such as a banner ad or a text link. It is often used for A/B testing and content-targeted ads.
      purpose: Acquisition campaign follow-up
      example: logolink
      optional: true
      recipients: ['acquisition']

ACTION-THEME:
  key: action-theme
  description: Thematic CTA
  parameters: 
    - key: event_slug
      description: The event slug
      purpose: Subject segmentation - improving service
      example: convention-fin-de-vie
      recipients: ['product']
    - key: visitor_id
      description: Unique visitor identifier
      purpose: Segmentation by unique visitor
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['product']
    - key: theme_label
      description: Label of the thematic
      purpose: Relevance of themes - service improvement
      example: cout de la vie
      recipients: ['product']
    - key: language
      description: Interface language
      purpose: Language segmentation - improving service
      recipients: ['product']
    - key: assembly_event_id
      description: The event identifier
      purpose: Data for control purpose
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['business']
    - key: visitor_id
      description: Unique visitor identifier
      purpose: Segmentation by unique visitor
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['business']
    - key: session_id
      description: Session identifier
      purpose: Segmentation by session
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['business']
    - key: assembly_event_id
      description: The event identifier
      purpose: Data for control purpose
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['acquisition']
    - key: visitor_id
      description: Unique visitor identifier
      purpose: Segmentation by unique visitor
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['acquisition']
    - key: session_id
      description: Session identifier
      purpose: Segmentation by session
      example: 00000000-0000-0000-0000-000000000000
      recipients: ['acquisition']
    - key: utm_campaign
      description: Identifies a specific product promotion or strategic campaign
      purpose: Acquisition campaign follow-up
      example: convention_france
      optional: true
      recipients: ['acquisition']
    - key: utm_source
      description: Identifies which site sent the traffic, and is a required parameter.
      purpose: Acquisition campaign follow-up
      example: google
      optional: true
      recipients: ['acquisition']
    - key: utm_term
      description: Identifies search terms
      purpose: Acquisition campaign follow-up
      example: running+shoes
      optional: true
      recipients: ['acquisition']
    - key: utm_content
      description: Identifies what specifically was clicked to bring the user to the site, such as a banner ad or a text link. It is often used for A/B testing and content-targeted ads.
      purpose: Acquisition campaign follow-up
      example: logolink
      optional: true
      recipients: ['acquisition']




