image: makeorg/docker-arch-docker:latest

variables: &global_variables
  IMAGE_NAME: "make-widget-runner"
  IMAGE_TARGET: "widget-production"
  IMAGE_PATH: "apps/widget/Dockerfile"
  YARN_VERSION: "1.22.5"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.cache
    - node_modules

stages:
  - check
  - build
  - merge
  - deploy

.check:
  stage: check
  except: 
    - production
  image: "node:16.9-alpine"
  before_script: 
    - node -v
    - export YARN_VERSION="$YARN_VERSION"
    - yarn install --check-files

check:
  extends: .check
  script:    
    - yarn workspace @make.org/widget translation

.build:
  stage: build
  tags:
    - docker
  except: 
    - production
  before_script: 
    - export IMAGE_VERSION=`git rev-parse --short=10 HEAD`
    - mkdir -p /var/lib/docker
    - mount -t tmpfs -o size=12G tmpfs /var/lib/docker
    - if [ ! -e /var/run/docker.sock ]; then DOCKER_DRIVER=overlay2 dockerd & fi
    - until docker ps; do echo "waiting for docker to be up..."; sleep 0.5; done
    - docker login "https://$NEXUS_URL" --username "$NEXUS_USER" --password "$NEXUS_PASSWORD"

build-widget:
  extends: .build
  script:
    - echo $(docker pull $NEXUS_URL/$IMAGE_NAME:$IMAGE_VERSION)
    - >
      if [[ -z $(docker images -q $NEXUS_URL/$IMAGE_NAME:$IMAGE_VERSION) ]];then
        DOCKER_BUILDKIT=1 docker build --rm -f $IMAGE_PATH -t $NEXUS_URL/$IMAGE_NAME:$IMAGE_VERSION --target $IMAGE_TARGET .
        docker push $NEXUS_URL/$IMAGE_NAME:$IMAGE_VERSION
      fi
    - docker tag $NEXUS_URL/$IMAGE_NAME:$IMAGE_VERSION $NEXUS_URL/$IMAGE_NAME:$CI_COMMIT_REF_NAME-latest
    - docker push $NEXUS_URL/$IMAGE_NAME:$CI_COMMIT_REF_NAME-latest

deploy-widget-preproduction:
  stage: deploy
  environment:
    name: preproduction
  only:
    - preproduction
  script:
    - >
      curl -D - -X "POST"
      -H "Accept: application/json"
      -H "Content-Type: application/x-www-form-urlencoded"
      -H "X-Rundeck-Auth-Token: $WIDGET_RUNDECK_PREPROD_TOKEN"
      --data-urlencode "argString=-version $CI_COMMIT_REF_NAME-latest"
      $RUNDECK_PREPROD_URL/api/16/job/$WIDGET_RUNDECK_PREPROD_JOB_ID/run

deploy-widget-production:
  stage: deploy
  environment:
    name: production
  only:
    - production
  script:
    - >
      curl -D - -X "POST"
      -H "Accept: application/json"
      -H "Content-Type: application/x-www-form-urlencoded"
      -H "X-Rundeck-Auth-Token: $WIDGET_RUNDECK_PROD_TOKEN"
      --data-urlencode "argString=-version $CI_COMMIT_REF_NAME-latest"
      $RUNDECK_PROD_URL/api/16/job/$RUNDECK_PROD_JOB_ID/run

merge-widget-to-prod:
  stage: merge
  when: manual
  only:
    - preproduction
  allow_failure: false
  script:
    - mkdir -p ~/.ssh/
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
    - echo "${DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - export CI_PUSH_REPO=`echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`
    - echo "Target repo is ${CI_PUSH_REPO}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git remote set-url origin "${CI_PUSH_REPO}"
    - git checkout production
    - git merge --ff-only origin/preproduction
    - git push origin production:production