export enum URL {
  JOBS_LINK = 'https://about.make.org/jobs',
  JOBS_LINK_DE = 'https://about.make.org/de/jobs-de',
  MODERATION_CHARTER_FR_LINK = 'https://about.make.org/moderation',
  MODERATION_CHARTER_EN_LINK = 'https://about.make.org/en/moderation',
  MODERATION_CHARTER_DE_LINK = 'https://about.make.org/de/moderation-charter',
  MODERATION_CHARTER_UK_LINK = 'https://about.make.org/uk/moderation',
  MODERATION_CHARTER_CS_LINK = 'https://about.make.org/cs/moderation',
  ABOUT_MAKE_LINK = 'https://about.make.org/',
  DOTATION_FUNDS_LINK = 'https://foundation.make.org',
  NEWS_LINK_FR = 'https://about.make.org',
  NEWS_LINK_DE = 'https://about.make.org/de/blog',
  NEWS_LINK_EN = 'https://about.make.org/en/blog',
  PRESS_DETAILS_LINK = 'https://about.make.org/les-medias-en-parlent',
}
