import { StateRoot } from '@make.org/types';
import fr from '../../i18n/fr.json';

export const initDevState = (initialState: StateRoot): StateRoot => ({
  ...initialState,
  appConfig: {
    ...initialState.appConfig,
    source: 'core',
    translations: { fr: { translation: fr } },
    countriesWithConsultations: [
      'AT',
      'BE',
      'BG',
      'BR',
      'CA',
      'CH',
      'CN',
      'CY',
      'CZ',
      'DE',
      'DK',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'HR',
      'HU',
      'IE',
      'IN',
      'IS',
      'IT',
      'JP',
      'LI',
      'LT',
      'LU',
      'LV',
      'MT',
      'NL',
      'NO',
      'PL',
      'PT',
      'RO',
      'RU',
      'SE',
      'SI',
      'SK',
      'US',
    ],
  },
});
