#!/bin/sh

# Run the translation and documentation checks
yarn workspace @make.org/front translation && \
yarn workspace @make.org/front documentation && \
yarn workspace @make.org/widget translation && \
yarn workspace @make.org/assembly-ui documentation && \

# Run the linter and the tests
yarn eslint ./ && \
yarn tsc --noEmit && \
yarn jest && \

# Run the code duplication detector
yarn jscpd


# recursively remove a directory but exclude prisma


