#!/bin/sh

# test apps/content
# If the content app has changed, run the tests and the linter
if git diff --name-only origin/preproduction | grep -q "^apps/content/"; then
  yarn workspace @make.org/content test
  yarn workspace @make.org/content lint
fi

# Run the translation and documentation checks
yarn workspace @make.org/front translation && \
yarn workspace @make.org/front documentation && \
yarn workspace @make.org/widget translation && \

# Run the linter and the tests
yarn eslint ./ && \
yarn tsc --noEmit && \
yarn jest && \

# Run the code duplication detector
yarn jscpd


# recursively remove a directory but exclude prisma


